[package]
name = "tls"
version = "0.1.0"
edition = "2021"

[dependencies]
ring = "0.17.8"
rustls-pki-types = { version = "1.10.1", features = ["std"] }
log = "0.4.25"
futures = { version = "0.3.31", features = ["std"] }
